Task\TaskBundle\Entity\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        price:
            type: decimal
    manyToOne:
          category:
              targetEntity: Category
              inversedBy: products
              joinColumn:
                  name: category_id
                  referencedColumnName: id